baseURL = "https://stackacademytv.github.io/JAMSite/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
