baseURL = "https://frosty-kilby-883dfb.netlify.com/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
  home = ["HTML", "JSON"]
